const DATA = {
  'Amazon Silk': 'amazon.png',
  'Android Browser': 'android.png',
  'Bada': null,
  'BlackBerry': null,
  'Chrome': 'chrome.svg',
  'Chromium': 'chromium.png',
  'Epiphany': 'epiphany.svg',
  'Firefox': 'firefox.svg',
  'Focus': 'firefox-focus.png',
  'Googlebot': null,
  'Internet Explorer': 'ie.png',
  'K-Meleon': null,
  'Maxthon': 'maxthon.png',
  'Microsoft Edge': 'edge.svg',
  'MZ Browser': null,
  'NAVER Whale Browser': null,
  'Opera Coast': 'opera-coast.jpg',
  'Opera': 'opera.svg',
  'PhantomJS': 'phantomjs.png',
  'Puffin': 'puffin.png',
  'QupZilla': null,
  'Safari': 'safari.png',
  'Sailfish': null,
  'SamsungBrowser': 'samsung-internet.svg',
  'SeaMonkey': 'seamonkey.png',
  'Sleipnir': null,
  'SlimerJS': 'slimerjs.png',
  'Swing': null,
  'Tizen': null,
  'UC Browser': 'uc.png',
  'Vivaldi': 'vivaldi.svg',
  'WebOS Browser': null,
  'Yandex Browser': 'yandex.png'
};

export default name => !DATA[name] ? null : `logos/${DATA[name]}`;
